baseURL = 'https://ninetwentythree.xyz/'
languageCode = 'en-us'
title = 'CMXXIII | NineTwentyThree'
theme = 'fromzero'

[markup.highlight]
style = 'dracula'

[params]
github = 'https://github.com/Voicedrew11'
youtube = 'https://www.youtube.com/@voicedrewxyz'
description = 'CMXXIII | NineTwentyThree — A personal site for posts, friends, and the odd note.'
og_image = '/images/5_CMXXIII.png'
